In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression

In [7]:
X, y, coef = make_regression(n_samples=2000, n_features=4,coef = True)
X.shape, y.shape

((2000, 4), (2000,))

In [10]:
# initializing weights and intercept with '0' as global variables
weights = np.array([0 for i in range(len(X[0]))])
intercept = 0
lr = 0.01

for i in range(5000): 

    yhat = np.dot(X, weights.T) + intercept                        

    dw = -(2/len(X)) * np.dot( X.T, (y - yhat) )                   # derivatives of loss w.r.t. weights 
    dc = -(2/len(X)) * np.sum( y - yhat )                          # derivative of loss w.r.t. intercept

    # parameter update
    weights = weights - lr * dw
    intercept = intercept - lr * dc

    if i%500==0:
        print(weights, intercept)

[1.23022151 0.32724511 0.45765689 1.96323668] -0.09537950441051153
[69.77010796 17.99862908 22.4399487  96.81935251] -0.0035163658383356084
[69.77973868 17.99981835 22.44080707 96.82337213] -6.172121230545702e-07
[69.77974006 17.9998184  22.44080713 96.82337241] -9.269531837954815e-11
[69.77974006 17.9998184  22.44080713 96.82337241] -3.388620439745515e-14
[69.77974006 17.9998184  22.44080713 96.82337241] -2.4415947874030026e-14
[69.77974006 17.9998184  22.44080713 96.82337241] -2.4096402927970995e-14
[69.77974006 17.9998184  22.44080713 96.82337241] -2.398106962950411e-14
[69.77974006 17.9998184  22.44080713 96.82337241] -2.3981069629504504e-14
[69.77974006 17.9998184  22.44080713 96.82337241] -2.39810696295049e-14


In [11]:
# we can compare the values from our model and the model trained by sklearn (values stored in coef variable)
coef

array([69.77974006, 17.9998184 , 22.44080713, 96.82337241])